default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: playground_development

test:
  <<: *default
  database: playground_test_<%= (branch = `git rev-parse --abbrev-ref HEAD 2>/dev/null`.chomp).empty? ? 'default' : branch.gsub(/\W/, '_') %>

staging:
  <<: *default
  database: playground_staging

production:
  username:
  password:
  adapter: postgresql
  host:
  port: 5432
  database: playground_production
  encoding: utf8
  collation: cs_CZ.UTF8
  min_messages: warning
  pool: 10
  timeout: 3000
